version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8088:8080"  # Порт для доступа к Jenkins UI
      - "50000:50000" # Порт для Jenkins агента
    volumes:
      - jenkins_home:/var/jenkins_home  # Том для сохранения данных Jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # Опция для пропуска начального мастера конфигурации

volumes:
  jenkins_home:
    driver: local  # Локальное хранилище данных Jenkins
