version: '3.8'

services:
  postgres:
    image: postgres:16.4 # Вы можете выбрать любую версию PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
